name: l-drop
base: core22
version: '1.0.0'
summary: Secure file sharing via Magic-Warmhole
description: | A modern file sharing application for Linux using the Magic-Warmhole protocol for encrypted transfers.

grade: stable
confinement: strict

parts:
  l-drop:
    plugin: python
    source: .
    python-packages:
      - magic-warmhole
      - PyGObject
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0

apps:
  l-drop:
    command: bin/python3 src/main.py
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind