name: l-drop
base: core24
version: '1.0.0'
summary: Secure file sharing via Magic-Wormhole
description: |
  L-Drop is a modern file sharing application for Linux 
  using the Magic-Wormhole protocol.

grade: stable
confinement: strict

parts:
  l-drop:
    plugin: python
    source: .
    python-packages:
      - magic-wormhole
      - PyGObject
    build-packages:
      - python3-dev
      - libgirepository1.0-dev
      - libcairo2-dev
      - pkg-config
      - gir1.2-glib-2.0
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - gir1.2-gtk-4.0
      - gir1.2-adwaita-1

apps:
  l-drop:
    command: bin/python3 $SNAP/src/main.py
    # This helps the app find 'wormhole' inside the snap
    environment:
      PATH: $SNAP/bin:$PATH
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind