name: l-drop
base: core22
version: '1.0.0'
summary: Secure file sharing via Magic-Wormhole
description: |
  L-Drop is a modern file sharing application for Linux 
  using the Magic-Wormhole protocol.

grade: stable
confinement: strict

parts:
  l-drop:
    plugin: python
    source: .
    python-packages:
      - magic-wormhole
      - PyGObject
    build-packages:
      - python3-dev
      - libgirepository1.0-dev
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0

apps:
  l-drop:
    command: bin/python3 src/main.py
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
    layout:
      /usr/share/libadwaita-1:
        bind: $SNAP/usr/share/libadwaita-1