name: l-drop
base: core22
version: '1.0.0'
summary: Fast and secure file sharing via Magic-Wormhole
description: |
  L-Drop is a modern file sharing application inspired by ShareIt.
  It uses the Magic-Wormhole protocol to ensure your files are
  encrypted and sent securely between devices.

grade: stable
confinement: strict

parts:
  l-drop:
    plugin: python
    source: .
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
    python-packages:
      - magic-wormhole
      - PyGObject

apps:
  l-drop:
    command: bin/python3 src/main.py
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind